---
genera:
  hosts:
    genera-vm:
      ansible_host: localhost
      ansible_port: 9000
  vars:
    genera_uid: 9000
    genera_gid: 9000
    genera_user: genera
    genera_group: genera
    genera_home: /genera
    genera_password: genera
    genera_gateway_ip: 192.168.2.1
    genera_virtual_ip: 192.168.2.2
